name: whelp_flutter_sdk
description: Whelp Live Chat SDK for Flutter targeting Android and iOS platforms
version: 0.3.0
homepage: https://whelp.co
repository: https://github.com/Whelp-Inc/whelp-flutter-sdk
issue_tracker: https://github.com/Whelp-Inc/whelp-flutter-sdk/issues

environment:
  sdk: '>=2.15.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  http: ^1.1.0
  url_launcher: ^6.1.14
  webview_flutter: ^4.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: