name: whelp_flutter_sdk
description: Whelp Live Chat SDK for Flutter Android and iOS projects
version: 0.2.2
homepage: https://whelp.co
repository: https://github.com/Whelp-Inc/whelp-flutter-sdk

environment:
  sdk: '>=2.15.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.2+3
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: